export enum PtfErrorCode {
  INSUFFICIENT_PTF_BALANCE = "INSUFFICIENT_PTF_BALANCE",
  WALLET_NOT_ACTIVATED = "WALLET_NOT_ACTIVATED",
  WALLET_BANNED = "WALLET_BANNED",
  OWNERSHIP_NOT_PROVEN = "OWNERSHIP_NOT_PROVEN",
  TASK_ALREADY_CLAIMED = "TASK_ALREADY_CLAIMED",
  TASK_IMMUTABLE = "TASK_IMMUTABLE",
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  TASK_NOT_OPEN = "TASK_NOT_OPEN",
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  PRIVATE_PROJECT_CONTRIBUTORS_HIDDEN = "PRIVATE_PROJECT_CONTRIBUTORS_HIDDEN",
  DEPENDENCY_NOT_VALIDATED = "DEPENDENCY_NOT_VALIDATED",
  COMMAND_NOT_ALLOWED = "COMMAND_NOT_ALLOWED",
  INVALID_CHAIN = "INVALID_CHAIN",
  INVALID_ADDRESS = "INVALID_ADDRESS",
  UNAUTHORIZED = "UNAUTHORIZED",
  LLM_NOT_CONFIGURED = "LLM_NOT_CONFIGURED",
  DAG_CYCLE_DETECTED = "DAG_CYCLE_DETECTED",
  ESCROW_INSUFFICIENT = "ESCROW_INSUFFICIENT",
}

export class PtfError extends Error {
  constructor(
    public readonly code: PtfErrorCode,
    message: string
  ) {
    super(message);
    this.name = "PtfError";
  }
}
