export enum PtfErrorCode {
  INSUFFICIENT_PTF_BALANCE = "INSUFFICIENT_PTF_BALANCE",
  WALLET_NOT_ACTIVATED = "WALLET_NOT_ACTIVATED",
  WALLET_BANNED = "WALLET_BANNED",
  OWNERSHIP_NOT_PROVEN = "OWNERSHIP_NOT_PROVEN",
  TASK_ALREADY_CLAIMED = "TASK_ALREADY_CLAIMED",
  TASK_IMMUTABLE = "TASK_IMMUTABLE",
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  TASK_NOT_OPEN = "TASK_NOT_OPEN",
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  PRIVATE_PROJECT_CONTRIBUTORS_HIDDEN = "PRIVATE_PROJECT_CONTRIBUTORS_HIDDEN",
  DEPENDENCY_NOT_VALIDATED = "DEPENDENCY_NOT_VALIDATED",
  COMMAND_NOT_ALLOWED = "COMMAND_NOT_ALLOWED",
  INVALID_CHAIN = "INVALID_CHAIN",
  INVALID_ADDRESS = "INVALID_ADDRESS",
  UNAUTHORIZED = "UNAUTHORIZED",
  LLM_NOT_CONFIGURED = "LLM_NOT_CONFIGURED",
  DAG_CYCLE_DETECTED = "DAG_CYCLE_DETECTED",
  ESCROW_INSUFFICIENT = "ESCROW_INSUFFICIENT",
  // Auth — registration / login
  INVALID_INPUT = "INVALID_INPUT",
  EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
  // GitHub repo verification
  INVALID_REPO_URL = "INVALID_REPO_URL",
  REPO_NOT_FOUND = "REPO_NOT_FOUND",
  REPO_NOT_PUBLIC = "REPO_NOT_PUBLIC",
  REPO_NO_LICENSE = "REPO_NO_LICENSE",
  REPO_LICENSE_NOT_OSI = "REPO_LICENSE_NOT_OSI",
  GITHUB_RATE_LIMITED = "GITHUB_RATE_LIMITED",
  GITHUB_API_ERROR = "GITHUB_API_ERROR",
  // Auth — GitHub
  GITHUB_ALREADY_LINKED = "GITHUB_ALREADY_LINKED",
  GITHUB_NOT_LINKED = "GITHUB_NOT_LINKED",
  // Auth — Wallet
  WALLET_NOT_LINKED = "WALLET_NOT_LINKED",
  // Auth — full identity required
  ACCOUNT_NOT_FULLY_LINKED = "ACCOUNT_NOT_FULLY_LINKED",
}

export class PtfError extends Error {
  constructor(
    public readonly code: PtfErrorCode,
    message: string
  ) {
    super(message);
    this.name = "PtfError";
  }
}
